### ISSUE TITLE
3个飘扬问题

### ISSUE THREAD

**Issue by wujihan2011** [cryptozoic-io/helpcenter#1]
你好，我是中国社区成员，咨询VCC的问题。
在cryptozoic APP里   ##，不小心点了3次飘扬计划，也就是锁了3次3600个VCC，能把币给我释放吗？还有飘扬计划每个账户能参与几次呢？
![1](https://user-images.githubusercontent.com/52445590/60496173-d7e38700-9ce4-11e9-937b-a389a8b8542b.jpg)

希望尽快收到回复，
感谢！

**Comment by cryptozoic-io** [comment]
show your vcc address, we will check it

**Comment by wujihan2011** [comment]
0x1e31f5d34ff20993bf5e8c407056e2ce342b8f46

**Comment by cryptozoic-io** [comment]
thanks for your commit, your vccs will returen soon after the confirmation

**Comment by xu328431467** [comment]
我的探索一直探索不到是怎么回事，还有转币区块确认

**Comment by xiyan5588** [comment]
我的探索也是探索不到，转币区块不确认
0x04a7db849fc76e429a0e8a399bb05476c5ea53ad
麻烦解决一下
