### ISSUE TITLE
你好，2019-7-02 收益 7月3日 没到账

### ISSUE THREAD

**Issue by 15374807774** [cryptozoic-io/helpcenter#10]
我的地址  0xb969f18ccb2290604d9f33af13cd4a032be019b5

![333](https://user-images.githubusercontent.com/52520055/60639989-80195d00-9e57-11e9-97c6-1c78db1c1ebe.jpg)
![33444](https://user-images.githubusercontent.com/52520055/60639991-83ace400-9e57-11e9-9916-619141623885.jpg)

**Comment by cryptozoic-io** [comment]
It is a rare bug and we are dealing with it.
We checked TxHash, and your VCC has been successfully received, but the transaction record is not recorded.
