### ISSUE TITLE
无法探索和转出代币

### ISSUE THREAD

**Issue by luo7568** [cryptozoic-io/helpcenter#14]
探索不成功，无法转出代币，一直在待确认状态！请帮忙解决一下，不然这个钱包没法使用！ 我的钱包地址：0xc9bf9e2af44027a4346b57898f4aaf0ce61d46f9  @cryptozoic-io  cryptozoic-io

**Comment by cryptozoic-io** [comment]
your transactions has been sent, thanks for your notice.
