### ISSUE TITLE
许愿锁仓时网络卡了，扣了我2笔，释放确只返回了一笔

### ISSUE THREAD

**Issue by lilianbing** [cryptozoic-io/helpcenter#15]
![image](https://user-images.githubusercontent.com/52650772/60790667-92b3cf00-a194-11e9-81f3-632a9e66be61.png)
![image](https://user-images.githubusercontent.com/52650772/60790681-a101eb00-a194-11e9-8fcd-d528ada9a8ca.png)
![image](https://user-images.githubusercontent.com/52650772/60790697-a828f900-a194-11e9-8cda-6622899f4f85.png)
![image](https://user-images.githubusercontent.com/52650772/60790706-afe89d80-a194-11e9-9c9b-bc09688ee0a6.png)

**Comment by lilianbing** [comment]
交易记录图已经上传，请管理员处理，谢谢！！

**Comment by cryptozoic-io** [comment]
your coins has been returned, sorry for the inconvenience.
