### ISSUE TITLE
飘扬释放后未收到vcc

### ISSUE THREAD

**Issue by aspark2018** [cryptozoic-io/helpcenter#16]
我于7月7日释放飘扬，今日客户端更新之前未接收都有显示未接收数量，更新后没有收到释放的vcc，未接收数量也清零，请帮忙处理，地址为0xa0cf65c74d1adfd27e7840679bfc686359fdeb1b

**Comment by cryptozoic-io** [comment]
your vccs are in sending queue, you will receive it 09/07
