### ISSUE TITLE
飘扬释放不了

### ISSUE THREAD

**Issue by zzlige** [cryptozoic-io/helpcenter#19]
账号地址：0x73ba0cf2ccc90f56cb5926e73551b6ef0dce7666
飘扬释放不了，释放时显示：NO CAID was found,
请帮忙处理一下。

**Comment by cryptozoic-io** [comment]
it's fixed, plz try again.

**Comment by zzlige** [comment]
已经正常释放了，谢谢



------------------ 原始邮件 ------------------
发件人: "cryptozoic project"<notifications@github.com>; 
发送时间: 2019年7月12日(星期五) 下午5:37
收件人: "cryptozoic-io/helpcenter"<helpcenter@noreply.github.com>; 
抄送: "李子哥"<380943761@QQ.com>; "Author"<author@noreply.github.com>; 
主题: Re: [cryptozoic-io/helpcenter] 飘扬释放不了 (#19)




it's fixed, plz try again.
