### ISSUE TITLE
关于VCC首发上交易所的一些推荐和建议

### ISSUE THREAD

**Issue by zzlige** [cryptozoic-io/helpcenter#20]
VCC的项目方：您们好！
      关于首发交易所，我代表一部分投资者的意见是这样的：上交易所是很重要的一件事情，我们的理解是，尽量上一些有流量的交易所，提币出入金比较快的。若没有流量，没有口碑，没有一点热度的交易所还不如不上。即使花点钱也没有关系也要上一两个有点热度的交易所。毕竟若大伙挣钱了，或看到能挣钱的希望，才会有动力！才会有信仰！才会去积极布道！这样VCC才会越来越好。
     基于投资者的一些币圈经验，这里给推荐几个用户体验比较好点的交易所希望项目方能够对接上，认为即使花点钱也是值得的。
 https://www.ceohk.bi/   香港CEO交易所，此交易所超级信仰群里有人可以对接。
 https://www.btcwinex.com/   Btcwinex交易所
https://www.bbkx.com/          BBKX交易所
https://www.sok.top/              SOK交易所
                                                 ZB交易所
                                                 ZBG 交易所
                                                 比特儿 交易所
                                                 BIT-Z   交易所
另外：BTCWINEX现在投7000万美金搞VDS矩阵，我们VCC也可以学习一下。

**Comment by cryptozoic-io** [comment]
thanks for your advice.
cryptozoic is a decentralized project. we are just the developing team .
we hope the communities and clubs all over the world can unite together to put VCC to the world. and then the popular exchange can add VCC trade pair automatically.
the exchange VCC will be trade on first depends on the communities and clubs. Chinese community is busy at talking to a list of exchanges positively. we will send it to the Chinese community.

last, thanks again
