### ISSUE TITLE
飘扬无法释放

### ISSUE THREAD

**Issue by 799563592** [cryptozoic-io/helpcenter#21]
飘扬释放不了，释放时显示：NO CAID was found, 试了几十次了，换了三个手机还是不行，请帮忙处理一下，万分感谢！
账号是：
0x6d18ae016df35302d63dbc4e0a3b8de9c1b9b3b1

**Comment by cryptozoic-io** [comment]
hi, you have released it successfully and you will receive the VCC 2019-7-13

**Comment by cryptozoic-io** [comment]
hi, you can release it now~
sorry for the inconvenience

**Comment by cryptozoic-io** [comment]
i'm closing this because the problem has been sovled
