### ISSUE TITLE
用vcc钱包转入到火币以太坊地址，怎么找回？

### ISSUE THREAD

**Issue by 1vcc** [cryptozoic-io/helpcenter#22]
你好，求助，vcc转币转错地址，转入到火币的以太坊地址里，求找回，vcc钱包地址0x7f087c2ef81a9bfe36cb9eded1559170052c50c3，火币的以太坊地址0xc646752a40890d94ad5a4fd890d28fa943138031
![41216BCB-3EF2-45BA-9905-47BB5944F251](https://user-images.githubusercontent.com/52856332/61171446-08aba200-a5aa-11e9-9188-dac040037b22.png)
![83AC68B5-F195-48F2-B5C0-31F0C932CB87](https://user-images.githubusercontent.com/52856332/61171447-09443880-a5aa-11e9-8b5f-7f0d0a70cb32.png)

**Comment by cryptozoic-io** [comment]
what is 火币 ?  is it the exchange https://www.huobi.com/?
if you send your VCC to the exchange, you must connect with the exchange supporting service or manual service. and submit the question to them, then ask them whether if they can use VCC-APP send the VCC back to you?

**Comment by 1vcc** [comment]
[你好，我现在在浏览器里为什么找不到我转入火币的那笔交易？
![Uploading AFC81A1C-1EF2-4093-B380-AB1750BCFBBE.jpeg…]()
![Uploading DDE68EC8-DCC9-4065-8951-14E9E1C1EE5F.png…]()
![Uploading 97EC04C6-E376-43EE-AAA9-108EFE612A5E.jpeg…]()
