### ISSUE TITLE
漂洋计划的奖励从10号开始就没有了

### ISSUE THREAD

**Issue by zyj359196551** [cryptozoic-io/helpcenter#23]

**Comment by cryptozoic-io** [comment]
the price is still going on
plz tell us your address to figure it out

**Comment by zyj359196551** [comment]
0xcfc3600e2fd4803bded1c8ab92272e05973e5a3e------------------ 原始邮件 ------------------
发件人: "cryptozoic project"<notifications@github.com>
发送时间: 2019年7月14日(星期天) 下午5:39
收件人: "cryptozoic-io/helpcenter"<helpcenter@noreply.github.com>;
抄送: "zyj359196551"<359196551@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [cryptozoic-io/helpcenter] 漂洋计划的奖励从10号开始就没有了 (#23)



the price is still going on
 plz tell us your address to figure it out
 
&mdash;
