### ISSUE TITLE
[你好，我现在在浏览器里为什么找不到我转入火币的那笔交易？

### ISSUE THREAD

**Issue by 1vcc** [cryptozoic-io/helpcenter#25]
转入火币交易所的那笔交易，为什么在区块浏览器查不到？vcc地址0x7f087c2ef81a9bfe36cb9eded1559170052c50c3

火币地址0xc646752a40890d94ad5a4fd890d28fa943138031

![CEABE652-EA8D-457B-9C44-4ECE07F9FC1B](https://user-images.githubusercontent.com/52856332/61215832-7d174a00-a73e-11e9-92dc-3b6b1af05ef9.png)
![72196F6D-F0A8-4BAB-8D41-50E3239C671C](https://user-images.githubusercontent.com/52856332/61215833-7dafe080-a73e-11e9-9643-26dbd274207f.png)
![D24A7131-F6FF-4269-B7DA-14882F3090C4](https://user-images.githubusercontent.com/52856332/61215834-7e487700-a73e-11e9-93e5-6d08a0a997c8.jpeg)
![F47B6480-C781-4B02-AEAE-FE157CC7AA24](https://user-images.githubusercontent.com/52856332/61215835-7e487700-a73e-11e9-9236-45bdce377c07.jpeg)

**Comment by cryptozoic-io** [comment]
the explorer can search trade by to address only
