### ISSUE TITLE
探索问题已经提币区块确认问题

### ISSUE THREAD

**Issue by xu328431467** [cryptozoic-io/helpcenter#3]

**Comment by hengjianYu** [comment]
Hello, that is, um, with regard to the function of exploration, ah, it is suggested that there should be such an option 10 times, 20 times, 100 times, so as to save the trouble of entering 50, er, at a time.

**Comment by cryptozoic-io** [comment]
@hengjianYu 
This is a nice suggestion.
But exploration is a complicated process, and we don't consider adding it in the near future.
