### ISSUE TITLE
ETH提币提到VCC地址  求找回

### ISSUE THREAD

**Issue by hitly1985** [cryptozoic-io/helpcenter#33]
我提币ETH提错地址！  提到交易所的VCC地址去了！  求项目方帮忙找回。。。
![image](https://user-images.githubusercontent.com/53590154/62340857-91678f00-b513-11e9-90b3-57dccb534344.png)

此地址为我的ZT  VCC的充值地址
![image](https://user-images.githubusercontent.com/53590154/62340933-e73c3700-b513-11e9-94cc-da380c4cce59.png)
求帮忙！

**Comment by cryptozoic-io** [comment]
So sorry that we are unable to control the ETH or VCC wallet address, please try to contact the Exchange.
