### ISSUE TITLE
vcc  missing

### ISSUE THREAD

**Issue by chang1203777** [cryptozoic-io/helpcenter#34]
two pieces of   vcc trasactions missing  !
wallet :   0x8f143178d0f39b30edb2ea558353a4a52cd5525d
 time :11:25:51am，July 17, 2019    
vcc amounts：3701
time： 11:20:55 am，july 17，2019
vcc amounts：3701
please figure  both out！
Thanks！

**Comment by cryptozoic-io** [comment]
We checked and found that there was no problem with the transaction. Maybe it's a bug in the transaction record and we will deal with it.

**Comment by chang1203777** [comment]
Thanks a lot for your reply.Coula u tell me the vcc wallet addres that from  "wallet : 0x8f143178d0f39b30edb2ea558353a4a52cd5525d" to?
1\time :11:25:51am，July 17, 2019
vcc amounts：3701
2\time :11:25:51am，July 17, 2019
vcc amounts：3701
