### ISSUE TITLE
飘扬计划释放不了

### ISSUE THREAD

**Issue by zhangchenxi321** [cryptozoic-io/helpcenter#36]
6个帐号，地址：
0x11c91525682db3e3b09aa824bbb92d494b44fd91
0x8196b03a3d5939223e477b059a4d015869b52e2d
0xa3e37741854cfb339d575315fe5556b0579f276a
0xcb100d7954021250feec1ab2cbe0993dd08bba80
0x71bcdd817b3369bdea89c71698636378f048913b
0x2d819155644ebd47590d2b00a70b3037fa06e286
飘扬计划释放不了，显示signa
ture authentication failed

**Comment by cryptozoic-io** [comment]
it's a bug and we have solved it.
