### ISSUE TITLE
两个飘扬问题

### ISSUE THREAD

**Issue by sahani713** [cryptozoic-io/helpcenter#4]
你好，我是中国社区成员，咨询VCC的问题。
在cryptozoic APP里 ##，不小心点了2次飘扬计划，也就是锁了2次3600个VCC，能把币给我释放吗？
![CBADF6C8-74D9-4B99-AA94-0FBD0FF55C04](https://user-images.githubusercontent.com/52484345/60570464-36bc0580-9da4-11e9-8a36-8b547e8390c0.jpeg)

**Comment by sahani713** [comment]
我的地址是0xfd1c1e0d2cc90ff594c01a361062ff9207ab3c35

**Comment by cryptozoic-io** [comment]
Sorry 4 that, and ur vcc will return ur wallet soon after the confirmation.
