### ISSUE TITLE
exchange

### ISSUE THREAD

**Issue by Mintank** [cryptozoic-io/helpcenter#8]
I'm from the exchange. It's a great honor to cooperating with your project.Invite your project to our exchange。Exchange：www.zt.com(China).

**Comment by cryptozoic-io** [comment]
It is a great thing that VCC has won your approval. But the future of VCC should be determined by all users and markets.VCC belongs to the world, not a single one can control its future.
You can join in Wish-making plan and express your views and expectations on VCC.
Ура!Ура!Ура!
