### ISSUE TITLE
探索多次没成功

### ISSUE THREAD

**Issue by xu569800** [cryptozoic-io/helpcenter#9]
昨天探索了很多次，一直没到账！
vcc地址:
0xcf67869a1f14626570eb144a8264dcb42f1efef2
![mmexport1562167095079](https://user-images.githubusercontent.com/52501622/60603785-fb8ff580-9de8-11e9-9fec-bc5c024c95ca.jpg)

**Comment by cryptozoic-io** [comment]
It‘s fixed, u can try it again.
